### ISSUE TITLE
Return existing shop rules

### ISSUE THREAD

**Issue by stursberg** [HPI-BP2017N2/ShopRulesGenerator#1]
I WANT TO provide the parser a set of shop specific rules for product attributes extraction
IN ORDER TO make the parser able to parse pages of this shop

Acceptance criteria:
- [x] if SRS has rules for a shop, it returns these when asked
- [x] if SRS has no rules for a shop, it returns "I have no rules for this shop" when asked-

Tasks:
- [x] get-request per route "/getRules/{shopId}"
- [x] if there is no rules available for asked shop, return 404

Notes:
- [x] for now, there is not important what is in rules
- [x] shop specific rules are currently stored in a repository

**Comment by deeps96** [comment]
Task:
To follow the standard, we need to change the response schema.
