### ISSUE TITLE
Generating rules

### ISSUE THREAD

**Issue by stursberg** [HPI-BP2017N2/ShopRulesGenerator#2]
I WANT TO be able to generate rules for shops if there are no rules for these in the repository
IN ORDER TO provide the parser rules for every shop

**Acceptance criteria:**
- [x] selectors should be explicit and minimal.
- [x] the number of Idealo offers that SRG gets from the DB can be set in config.
- [x] fetching of pages should be polite (delay between calls that can be set in config).
- [x] Use URLCleaner before fetching the HTML pages.

**Scenario:**
1. SRG gets a request from a parser with shopID.
2. SRG checks if the rules for this shopID already exist. If yes, follow step 7. If no, follow step 3.
3. SRG takes some offers of the shop from Idealo DB (the number can be defined in config).
4. SRG fetches shop page for every offer.
5. SRG searches on every page values of product attributes and builds the explicit selector for every occurrence of every product attribute. (no script tags for now)
6. SRG saves these selectors as a set of rules for this shop in the repository.
7. SRG returns the parser these rules.

**Relevant product attributes:**
- all unique ID (EAN, HAN, SKU etc)
- title
- category
- brand name
- price
- description

**NOTES:**
- As a selector should be used CSS-selectors.
- Set of rules should be presented as a JSON.
- No evaluation yet!
- Occurrence means: Node does contains exactly offer attribute value

**Comment by deeps96** [comment]
Tasks:

- [x] Load the seed data (sample offers) from idealo offer store
- [x] Fetch html pages for url of each offer
- [x] Implement selector generator
- [x] Search for each occurrence and use the selector generator
- [x] Build rule with selectors
- [x] Store rules into repository (DB)
- [x] Return rule
